name: Build

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  spring-boot-2:
    name: SpringBoot2
    uses: ./.github/workflows/check.yml
    with:
      test_spring_boot_version: 2.4.12
  spring-boot-3:
    name: SpringBoot3
    uses: ./.github/workflows/check.yml
    with:
      test_spring_boot_version: 3.1.1
  spring-boot-4:
    name: SpringBoot4
    uses: ./.github/workflows/check.yml
    with:
      test_spring_boot_version: 4.0.0
  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: [test-iteration-1, test-iteration-2, test-iteration-3, test-iteration-4, test-iteration-5]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: LocalPublish
        run: ./cftlib/gradlew -i publish
