name: Java CI

on:
  workflow_call:
inputs:
  test_spring_boot_version:
    required: false
    default: '2.4.12'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: |
          11
          17
        cache: 'gradle'
    - name: Set JDK 11 location
      run: echo "JDK_11=$JAVA_HOME_11_X64" >> "$GITHUB_ENV"
    - name: Build
      run: (cd cftlib;./gradlew -PtestSpringBootVersion=${INPUT_TEST_SPRING_BOOT_VERSION} -P check -i)
