name: Release

on:
  push:
    branches:
      - release
jobs:
  create_release_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/0.15.{{ github.run_id }}",
              sha: context.sha
            })
